package exception;

public interface ErrorCode {

    int COMMON_ERROR_CODE_START = 1000;

    int COMMON_ERROR_CODE_START1 = 0;

    int COMMON_ERROR_CODE_START2 = 0;

    int PLATFORM_ERROR_CODE_START = COMMON_ERROR_CODE_START + 1000;

    int MARKET_ERROR_CODE_START = COMMON_ERROR_CODE_START + 2000;

    int CONSOLE_ERROR_CODE_START = COMMON_ERROR_CODE_START + 3000;

    int APP_NAME_DUPLICATED = CONSOLE_ERROR_CODE_START + 1;

<<<<<<< HEAD
=======
    int ADMIN_ERROR_CODE_START1 = COMMON_ERROR_CODE_START + 4000;

    int ADMIN_ERROR_CODE_START2 = COMMON_ERROR_CODE_START + 5000;
>>>>>>> ee0d707bcb8c6bfc3017c6ba45298a1406db8b5e

}
